# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_retailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/service_orders')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_file', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/service_orders')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='retailer',
            name='file',
            field=models.FileField(upload_to='uploads/retailers'),
        ),
    ]
