# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170319_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/distributors')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='distributor',
            name='file',
            field=models.FileField(upload_to='uploads/distributors'),
        ),
    ]
